### ISSUE TITLE
can't find module from 'saicinpainting' saicinpainting.evaluation.utils import move_to_device

### ISSUE THREAD

**Issue by ZepaMK** [advimman/lama#105]
It seems I can't import the move_to_device. It is in the lama/bin/predict.py", line 14. I think the problem is that the package is missing in the sys.path. I've tried to change path names but It just cant find it.

**Comment by windj007** [comment]
Hi! Do you do `export PYTHONPATH="path/to/lama/folder"` as [stated in the readme](https://github.com/saic-mdal/lama#inference-)?

**Comment by NinnaFRC** [comment]
I have the same problem! I have already done `cd lama` and `export PYTHONPATH=.`

**Comment by windj007** [comment]
Set PYTHONPATH to absolute path. `.` is relative and thus depends on the directory from which you execute the command

**Comment by hamzanaeem1999** [comment]
It is still not good answer, Error is coming again if i set paths even absolute too

**Comment by minakshimathpal** [comment]
@hamzanaeem1999
I have used your code and checked my pwd. It points to /content/lama(working in colab). Still getting the same error

**Comment by hamzanaeem1999** [comment]
@minakshimathpal Check the path again and specify colon in start like. `":/content/lama"`
