### ISSUE TITLE
Modules not found

### ISSUE THREAD

**Issue by dillfrescott** [advimman/lama#142]
(lama) C:\Users\micro\Downloads\lama>python bin/predict.py model.path=.\big-lama indir=.\in outdir=.\output
Traceback (most recent call last):
  File "C:\Users\micro\Downloads\lama\bin\predict.py", line 14, in <module>
    from saicinpainting.evaluation.utils import move_to_device
ModuleNotFoundError: No module named 'saicinpainting'

(lama) C:\Users\micro\Downloads\lama>pip install saicinpainting
ERROR: Could not find a version that satisfies the requirement saicinpainting (from versions: none)
ERROR: No matching distribution found for saicinpainting

**Comment by saurabhsinha3682** [comment]
Use git-bash terminal.

**Comment by Suhask98** [comment]
Didn't work with Git bash as well..any other suggestion to install the package?

**Comment by Suhask98** [comment]
$ pip install saicinpainting
ERROR: Could not find a version that satisfies the requirement saicinpainting (from versions: none)
ERROR: No matching distribution found for saicinpainting

**Comment by arnavmehta7** [comment]
What i did was I moved that folder into the bin along with other folders

**Comment by MistersWang** [comment]
sys.path.append('./lama')
do this way

**Comment by senya-ashukha** [comment]
TY!
