### ISSUE TITLE
I have to say this code is written way too complicated

### ISSUE THREAD

**Issue by yingqichao** [advimman/lama#156]
It is really difficult to find a definition, for example, how "ratio_gin, ratio_gout" of each layer is defined, etc. It seems everything is wrapped up layer by layer.

Besides, I didn't find any clue of things like "SeBlock" or "LearnableSpatialTransformWrapper" in the paper, but they just appear in the codes, making the project harder to read.

**Comment by dragen1860** [comment]
by the way, what does "ablv2" means in configs folder.

**Comment by shash29-dev** [comment]
🤣
Well said. 
But with hydra and pytorch lightning it is written very well to do ablation studies.

**Comment by steinhaug** [comment]
also the libraries have been updated to they are broken on Google Colab, the inpainting bit using saicinpainting. :(

**Comment by xiximelon** [comment]
agree,i can't even debug correctly

**Comment by senya-ashukha** [comment]
I feel your pain, f you can improve the code --- please send pool request!
