### ISSUE TITLE
link is broken, can not download lama-models.zip?

### ISSUE THREAD

**Issue by dragen1860** [advimman/lama#157]
Dear all:
    I find the link is broken: 
```
curl -L $(yadisk-direct https://disk.yandex.ru/d/EgqaSnLohjuzAg) -o lama-models.zip

```

anyone can share the file on google drive or baidu netdisk?  thank you very much.

**Comment by senya-ashukha** [comment]
It works for me, do u have access from chrome to https://disk.yandex.ru/d/EgqaSnLohjuzAg ?

**Comment by CeoiZidung** [comment]
Hi~
I met the same problem as you did. I wanna ask whether you've fixed it yet?

**Comment by arnavmehta7** [comment]
Hey, kindly use a VPN to use that.

**Comment by Just-Eating** [comment]
same issue

**Comment by senya-ashukha** [comment]
Sorry for inconvenience ---- try that https://drive.google.com/drive/folders/1B2x7eQDgecTL0oh3LSIBDGj0fTxs6Ips?usp=drive_link ! 
and we will fix the repo! TY!
