### ISSUE TITLE
training is very slow

### ISSUE THREAD

**Issue by dragen1860** [advimman/lama#162]
Dear all:
   I found i have to train lama-fourier on 4xRTX3090 for 13 days. But the generator and discrimator size is rather medium, compared with nowadays big models. So why the training is so slow, what the bottleneck?? thank you.

**Comment by CodeMadUser** [comment]
> Dear all: I found i have to train lama-fourier on 4xRTX3090 for 13 days. But the generator and discrimator size is rather medium, compared with nowadays big models. So why the training is so slow, what the bottleneck?? thank you.

hello, I found that you have been able to train this model, could you please share your training log? I read the original training steps and I always get errors when I train. Very much looking forward to your reply.
eg.
Traceback (most recent call last):
  File "bin/gen_mask_dataset.py", line 11, in <module>
    from saicinpainting.evaluation.masks.mask import SegmentationMask, propose_random_square_crop
ModuleNotFoundError: No module named 'saicinpainting'

**Comment by Giri0808** [comment]
I add this line of code to the terminal and I don't get this error
export TORCH_HOME=$(pwd) && export PYTHONPATH=$(pwd)

**Comment by senya-ashukha** [comment]
@Giri0808 TY!

**Comment by zhao2000hhh** [comment]
which dataset you train need 13 days？ Places2？
