### ISSUE TITLE
How to  inpaint a pinstripe image?

### ISSUE THREAD

**Issue by wangchangquan** [advimman/lama#203]
I use lama to inpaint pinstripe image,However, the effect is very bad. The reason may be that the feature of the fine stripes is lost when the lama network is doing the initial down-sampling. Therefore, what should I do to better inpaint the fine stripes image？
![batch0000214](https://user-images.githubusercontent.com/40132685/212378371-7368ecce-8d3b-404d-8c78-0e72354ef8f8.jpg)

**Comment by windj007** [comment]
This is a very difficult case. I'd not expect that a pretrained LaMa would carry that out - too big domain shift. Have you tried retraining on your data?

Btw, you might need a different architecture for that, e.g. [SWAGAN](https://github.com/rinongal/swagan).
