### ISSUE TITLE
Zombie Picture on Huggingface

### ISSUE THREAD

**Issue by taucontrib** [advimman/lama#216]
The Huggingface demo is only outputting a disturbing picture of a female zombie. 
Dont really get this kind of humour tbh...

**Comment by windj007** [comment]
Hard to help without more details.

**Comment by taucontrib** [comment]
https://huggingface.co/spaces/akhaliq/lama 

No matter what I uploaded & what mask i chose, the output would be a zombie-picture

**Comment by windj007** [comment]
1. Cannot confirm: I've just uploaded a couple of different images - and the results were fine.
2. Could you please show what you're getting? Without that, it is hard to guess.
3. This space is maintained by @AK391, I cannot help with it.

**Comment by taucontrib** [comment]
I tried again and the output was normal. No idea. Thanks!

**Comment by MacM2Pro** [comment]
As for me, this space is endlessly preparing. I can't use the program there
