### ISSUE TITLE
[Question] AWS Neuron Compilation

### ISSUE THREAD

**Issue by spy1233** [advimman/lama#219]
Hello, I'm newbie on deep learning area.
I'm trying to utilize LaMa on AWS Inf1 instance.
According to [the documentation](https://docs.aws.amazon.com/dlami/latest/devguide/tutorial-inferentia-pytorch-neuron.html), sample compilation code is like:
```
import torch
import numpy as np
import os
import torch_neuron
from torchvision import models

image = torch.zeros([1, 3, 224, 224], dtype=torch.float32)

## Load a pretrained ResNet50 model
model = models.resnet50(pretrained=True)

## Tell the model we are using it for evaluation (not training)
model.eval()
model_neuron = torch.neuron.trace(model, example_inputs=[image])

## Export to saved model
model_neuron.save("resnet50_neuron.pt")
```

Here are my questions.
1. Can LaMa model be complied to model for Inf1 chip?
2. The sample code above `torch.neuron.trace` function requires `example_inputs`. I'd like to know example_inputs for LaMa model.

I'd like to share this trial to the community if I succeed.

Thank you so much.

**Comment by senya-ashukha** [comment]
> Can LaMa model be complied to model for Inf1 chip?

probably it can but I am not sure how hard it wold be! if you can do that please let us know!
