### ISSUE TITLE
Why you only use half of the feature for FFT?

### ISSUE THREAD

**Issue by ChrisChen1023** [advimman/lama#226]
Hi there,

Thanks for sharing the work, which is excellent! I  am curious, in FFC, why you only use half of the feature for FFT. Did you ever try using different scales of features to divide Local and Global? For example 3/4 for LOCAL, and 1/4 for GLOBAL? Also, in both of the 'Local' and the 'Global', you actually use convolution operation  3 times and FFT only once, then do the feature fusion. Did you ever try dealing with Global feature all in frequency domain. In other words, have you tried making frequency domain operations a larger proportion of your FFC? And what inspired you to do this decision?

Thanks for your attention!

Best 

Chris

**Comment by senya-ashukha** [comment]
To the best of my knowledge we did not do a lot of experiments on that! please let us know if you try!
