### ISSUE TITLE
Is there a simple example just using the model?

### ISSUE THREAD

**Issue by menandro** [advimman/lama#227]
Is there an inference code without any of the magical tools and techniques provided here?

**Comment by menandro** [comment]
Thank you. What I meant was a python code, not a command line execution.

**Comment by Amazingldl** [comment]
I am looking for this too, the code is too complicated for me.

**Comment by sriomsubham** [comment]
Yes the code is very complicated. 
If you want to set the image  and mask you can go to saicinpainting/evaluation/data.py , read this file.

**Comment by Amazingldl** [comment]
> Yes the code is very complicated. If you want to set the image and mask you can go to saicinpainting/evaluation/data.py , read this file.

Thank you!

**Comment by algopert** [comment]
Hi :)

Firstly, thanks for sharing such a great tool!

Is there a minimal snippet where the input data is 1 image and 1 mask and uses a big-lama model?

**Comment by Amazingldl** [comment]
Exactly what I expected!

Algorithm Expert ***@***.***>于2023年4月19日 周三00:46写道：

**Comment by algopert** [comment]
Just did it. But not for refine module...

Need to dig in...

**Comment by s-tweed** [comment]
I successfully just inserted some hard-coded values in the omegaconf object in predict.py, which allows me to run it from python (not CLI). You need to init the default YAML config however (I'm not familiar with Hydra but I believe that is what the Hydra decorator does).

**Comment by himmetozcan** [comment]
just use this https://github.com/enesmsahin/simple-lama-inpainting

**Comment by senya-ashukha** [comment]
TY @himmetozcan addad to readme!
