### ISSUE TITLE
LaMa Pre-trained Model License (from authors of Inpaint Anything)

### ISSUE THREAD

**Issue by geekyutao** [advimman/lama#230]
Dear LaMa authors,

Greeting! We are the authors of [Inpaint Anything](https://github.com/geekyutao/Inpaint-Anything).

First, we would like to say thank you. Our work [Inpaint Anything](https://github.com/geekyutao/Inpaint-Anything) uses LaMa to perform inpainting and achieves amazing results. Some users encountered troubles when downloading the pre-trained model weights of LaMa. If possible, would you mind uploading the weights to other cloud such as google drive? And may I ask if the license of the weights is the same as this repo  (Apache 2.0)? 

Best regards, 
Authors of Inpaint Anything

**Comment by senya-ashukha** [comment]
amazing work added to readme! on the license --- I'm quite sure that repo says apache 2.0 ;-)
