### ISSUE TITLE
Best results possible

### ISSUE THREAD

**Issue by s-tweed** [advimman/lama#233]
I cloned the repo, downloaded the big-lama weights and tried removing the red photos from this image: https://unsplash.com/photos/y9BTlqIC-OY.

Admittedly it is a difficult task, and the results are not too great. However just as a test I uploaded the same photo to https://cleanup.pictures/ and tried again, and the output was far better. Is there something I'm missing in my setup to improve the results, similar to what cleanup.pictures is getting? I get the "missing detectron v2" error others have mentioned, but I saw in other questions that it shouldn't be an issue. Anything else I need to do?

Otherwise fantastic tool! In other test cases it is far superior to photoshop and is coming in very handy already.

EDIT: I noticed cleanup.pictures is down-sizing the image, so I tried resizing my image to 1024px in the height and the result is MUCH better. Instead of a mushy brick it was actually able to infer she shape of the glasses, even in the reflection (which is pretty insane). Why is it so much worse on the image when it is 2880px tall?

- Spencer

**Comment by senya-ashukha** [comment]
The model was trained on small images 256x256 --- you would expect some degradation as resolution increases!
