### ISSUE TITLE
The URLs for https://disk.yandex.ru/d/... have all expired

### ISSUE THREAD

**Issue by GuoRui0402** [advimman/lama#235]
The URLs for https://disk.yandex.ru/d/... have all expired, making it impossible to download the pre-trained model.

**Comment by ladyxuxu** [comment]
me too

**Comment by Damon-GSY** [comment]
me too

**Comment by ZhengMengbin** [comment]
> The URLs for https://disk.yandex.ru/d/... have all expired, making it impossible to download the pre-trained model.

Whether you have solved？

**Comment by senya-ashukha** [comment]
Hey! really sorry for that 

Here they are https://drive.google.com/drive/folders/1B2x7eQDgecTL0oh3LSIBDGj0fTxs6Ips?usp=drive_link 

we will update readme!
