### ISSUE TITLE
how to continue training?

### ISSUE THREAD

**Issue by Jaep0805** [advimman/lama#236]
After pausing the training process, I want to recontinue the training progress from the stop point. 
Is this implemented? and if so how to do this?

**Comment by larsupb** [comment]
You can reference your resume checkpoint in the config e.g. "/lama/configs/training/trainer/any_gpu_large_ssim_ddp_final.yaml"
`
kwargs:
  resume_from_checkpoint:  <absolute path to your chk file>
`

**Comment by senya-ashukha** [comment]
TY @larsupb!
