### ISSUE TITLE
pre-trained

### ISSUE THREAD

**Issue by aiyb1314** [advimman/lama#238]
Training failed due to [Errno 2] No such file or directory:    ade20k/ade20k-resnet50dilated-ppm_deepsup/encoder_epoch_20.pth':

**Comment by edvardHua** [comment]
same error

**Comment by senya-ashukha** [comment]
Sorry for inconvenience ---- try that https://drive.google.com/drive/folders/1B2x7eQDgecTL0oh3LSIBDGj0fTxs6Ips?usp=drive_link !

**Comment by aiyb1314** [comment]
The pre-training weights are for the following paper: Feature Refinement to Improve High Resolution Image Inpainting.



At 2023-11-19 03:16:10, "Arsenii Senya Ashukha" ***@***.***> wrote:

Sorry for inconvenience ---- try that https://drive.google.com/drive/folders/1B2x7eQDgecTL0oh3LSIBDGj0fTxs6Ips?usp=drive_link !
