### ISSUE TITLE
lama train

### ISSUE THREAD

**Issue by yangjq321** [advimman/lama#239]
May I ask why I don't save the models for each stage when training my dataset in Lama, and the last saved model is a 0 file? What should I do if I want to save the models for each stage and the saved model is a pth file? thanks
<img width="1084" alt="image" src="https://github.com/advimman/lama/assets/116736199/d3798f01-68d7-4913-948d-29f58d1e1be3">

**Comment by senya-ashukha** [comment]
you can add saving in training loop!

**Comment by yangjq321** [comment]
> 您可以在训练循环中添加保存！

Thank you very much!
