### ISSUE TITLE
How to adjust val_check_interval

### ISSUE THREAD

**Issue by clcllllll** [advimman/lama#252]
Error occurred when training my own dataset：
ValueError: `val_check_interval` (25000) must be less than or equal to the number of the training batches (573). If you want to disable validation set `limit_val_batches` to 0.0 instead.

**Comment by whitefish132** [comment]
Hi! I met the same problem and I changed "limit_train_batches" in "configs/training/trainer/any_gpu_large_ssim_ddp_final.yaml". 
 I'm wondering if there's a more elegant way to change the parameter (like, change it directly in the command line...

**Comment by senya-ashukha** [comment]
TY @whitefish132
