### ISSUE TITLE
docker: `ERROR: failed to solve: nvidia/cuda:10.2-runtime-ubuntu18.04`

### ISSUE THREAD

**Issue by osalbahr** [advimman/lama#263]
How can I deploy this model in a container?

I was trying to use the "[3. Docker: No actions are needed 🎉](https://github.com/advimman/lama#environment-setup)" method and I am not sure how to get to that state. I assumed it is by using the `./docker/build.sh`. However, it seems that it is using an old version of `nvidia/cuda` (probably kept for reproducibility purposes):

```console
[USER:HOST] lama$ ./docker/build.sh 
[+] Building 0.4s (3/3) FINISHED                                 docker:default
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 1.61kB                                     0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 2B                                            0.0s
 => ERROR [internal] load metadata for docker.io/nvidia/cuda:10.2-runtime  0.3s
------
 > [internal] load metadata for docker.io/nvidia/cuda:10.2-runtime-ubuntu18.04:
------
Dockerfile:1
--------------------
   1 | >>> FROM nvidia/cuda:10.2-runtime-ubuntu18.04
   2 |     
   3 |     RUN apt-get update && \
--------------------
ERROR: failed to solve: nvidia/cuda:10.2-runtime-ubuntu18.04: docker.io/nvidia/cuda:10.2-runtime-ubuntu18.04: not found
```

**Comment by amangupta2303** [comment]
@osalbahr I'm getting the same error. Did you find any solution?

**Comment by osalbahr** [comment]
> @osalbahr I'm getting the same error. Did you find any solution?

I haven’t. It looks like Nvidia/cuda discontinued ubuntu 18 support https://hub.docker.com/r/nvidia/cuda

**Comment by amangupta2303** [comment]
@osalbahr I got the solution! Providing you the working dockerfile for LAMA model. It works on the latest pytorch and cuda versions. 

FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update && \
    apt-get install -y libgl1-mesa-glx && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y libglib2.0-0

RUN python -m pip install --upgrade pip && \
    pip install -U pip numpy scipy torchvision tensorflow joblib matplotlib pandas \
    pytorch-lightning==1.2.9 tabulate easydict==1.10 kornia==0.5.0 webdataset \
    packaging gpustat tqdm pyyaml hydra-core==1.1.0.dev6 scikit-learn==1.3.1 tabulate && \
    pip install scikit-image==0.22.0 torchtext==0.6.0 albumentations==0.5.2 opencv-python==4.8.1.78

RUN useradd -ms /bin/bash admin

WORKDIR /workspace

RUN chown -R admin:admin /workspace && \
    chmod 777 /workspace

USER admin

**Comment by senya-ashukha** [comment]
TY @amangupta2303 !
