### ISSUE TITLE
ValueError: `Dataloader` returned 0 length. Please make sure that it returns at least 1 batch

### ISSUE THREAD

**Issue by HappyYuji** [advimman/lama#264]
I am trying to train a model on my dataset (which consists of my images and masks), 
but I encountered the following error:

ValueError: `Dataloader` returned 0 length. Please make sure that it returns at least 1 batch.

I added a LOGGER in the `train_dataloader` method located in `saicinpainting>training>trainers>base.py`, but it didn't work.

The LOGGER in the 'val_dataloader' is working successfully.

What can I do?

**Comment by amangupta2303** [comment]
@HappyYuji It might be an internal error indicating that image or masks are missing in the directory specified. Try to carefully repeat the exact steps defined in the readme file.

**Comment by HappyYuji** [comment]
@amangupta2303 Thank you for your interest. However, I followed the 'Create your data' step exactly as instructed. I can see the LOGGER INFO displaying the path to the 'val' directory I specified accurately, and I have placed both the image and the mask in the directory (image.png, image_mask.png........)

**Comment by amangupta2303** [comment]
@HappyYuji Maybe then you should once check your config.yaml to verify if your paths are correct or not. Just like the below image reference.

![Screenshot from 2023-10-24 11-05-46](https://github.com/advimman/lama/assets/105497860/e0ad0c68-99c0-43bf-a43a-39d6899bb564)

**Comment by HappyYuji** [comment]
@amangupta2303 It was not config.yaml problem. I placed the images directly under the "val" folder with names like "val/image1.png," "val/image1_mask.png," "val/image2.png," "val/image2_mask.png," and so on. However, I resolved it by creating additional subfolders under "val," such as "val/random_medium/image1.png," and so on. The "ValueError: Dataloader returned 0 length" error is no longer occurring. Thank you!

**Comment by WJDNJSDJ** [comment]
@HappyYuji  Hello, I have placed both the images and masks for training and testing in the same folder (image1.jpg, image1_mask001.jpg........ And by creating other subfolders under "val", but the problem still appears, do you need to change the program? Looking forward to your reply, I wish you a happy life and all the best!
