### ISSUE TITLE
Cannot Download File

### ISSUE THREAD

**Issue by 385yash** [advimman/lama#265]
File access is restricted
Files shared by the owner are not viewable. This happened because his Disk was full.

**Comment by springsha** [comment]
i meet the same error！ T T
what can we do

**Comment by humiao1993** [comment]
Can the model be downloaded elsewhere?

**Comment by TayJen** [comment]
+, same, wanted to download pretrained model

**Comment by senya-ashukha** [comment]
Sorry for inconvenience ---- try that https://drive.google.com/drive/folders/1B2x7eQDgecTL0oh3LSIBDGj0fTxs6Ips?usp=drive_link ! and we will fix the repo! TY!
