### ISSUE TITLE
Can't download the dataset

### ISSUE THREAD

**Issue by songllz** [advimman/lama#269]
When I download the Places2 and the test images, it will cause error like picture showing...what should I do with it?
![1697866982177](https://github.com/advimman/lama/assets/126565454/9f865d1f-ec8e-4e86-b0b5-9e38bfca4979)

**Comment by FinCottle44** [comment]
same error - the link points to something about the users disk being full?

**Comment by FinCottle44** [comment]
believe this should fix
#https://github.com/advimman/lama/issues/260

**Comment by songllz** [comment]
oh! Thank you! I'll try it soon

**Comment by AugustasMacys** [comment]
@FinCottle44 Still the same issue

**Comment by ZhengMengbin** [comment]
> When I download the Places2 and the test images, it will cause error like picture showing...what should I do with it? ![1697866982177](https://user-images.githubusercontent.com/126565454/277090408-9f865d1f-ec8e-4e86-b0b5-9e38bfca4979.png)

Whether you have solved？

**Comment by songllz** [comment]
no, the I don't find where to download the dataset

**Comment by senya-ashukha** [comment]
Sorry for inconvenience ---- try that https://drive.google.com/drive/folders/1B2x7eQDgecTL0oh3LSIBDGj0fTxs6Ips?usp=drive_link ! and we will fix the repo! TY!
