### ISSUE TITLE
Link to pretrained model and test dataset seems to be not working

### ISSUE THREAD

**Issue by Nineves** [advimman/lama#272]
I tried with the link provided in #260 but still got errors. 
```
curl -L $(yadisk-direct https://disk.yandex.ru/d/kHJkc7bs7mKIVA) -o big-lama.zip
Traceback (most recent call last):
  File "/home/wangyuxi/miniconda3/envs/lama/bin/yadisk-direct", line 8, in <module>
    sys.exit(main())
  File "/home/wangyuxi/miniconda3/envs/lama/lib/python3.6/site-packages/wldhx/yadisk_direct/main.py", line 23, in main
    print(*[get_real_direct_link(x) for x in args.sharing_link], sep=args.separator)
  File "/home/wangyuxi/miniconda3/envs/lama/lib/python3.6/site-packages/wldhx/yadisk_direct/main.py", line 23, in <listcomp>
    print(*[get_real_direct_link(x) for x in args.sharing_link], sep=args.separator)
  File "/home/wangyuxi/miniconda3/envs/lama/lib/python3.6/site-packages/wldhx/yadisk_direct/main.py", line 12, in get_real_direct_link
    return pk_request.json()['href']
KeyError: 'href'
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
```

**Comment by ZhengMengbin** [comment]
> I tried with the link provided in #260 but still got errors.
> 
> ```
> curl -L $(yadisk-direct https://disk.yandex.ru/d/kHJkc7bs7mKIVA) -o big-lama.zip
> Traceback (most recent call last):
>   File "/home/wangyuxi/miniconda3/envs/lama/bin/yadisk-direct", line 8, in <module>
>     sys.exit(main())
>   File "/home/wangyuxi/miniconda3/envs/lama/lib/python3.6/site-packages/wldhx/yadisk_direct/main.py", line 23, in main
>     print(*[get_real_direct_link(x) for x in args.sharing_link], sep=args.separator)
>   File "/home/wangyuxi/miniconda3/envs/lama/lib/python3.6/site-packages/wldhx/yadisk_direct/main.py", line 23, in <listcomp>
>     print(*[get_real_direct_link(x) for x in args.sharing_link], sep=args.separator)
>   File "/home/wangyuxi/miniconda3/envs/lama/lib/python3.6/site-packages/wldhx/yadisk_direct/main.py", line 12, in get_real_direct_link
>     return pk_request.json()['href']
> KeyError: 'href'
> curl: no URL specified!
> curl: try 'curl --help' or 'curl --manual' for more information
> ```

Whether you have solved？

**Comment by Nineves** [comment]
> > I tried with the link provided in #260 but still got errors.
> > ```
> > curl -L $(yadisk-direct https://disk.yandex.ru/d/kHJkc7bs7mKIVA) -o big-lama.zip
> > Traceback (most recent call last):
> >   File "/home/wangyuxi/miniconda3/envs/lama/bin/yadisk-direct", line 8, in <module>
> >     sys.exit(main())
> >   File "/home/wangyuxi/miniconda3/envs/lama/lib/python3.6/site-packages/wldhx/yadisk_direct/main.py", line 23, in main
> >     print(*[get_real_direct_link(x) for x in args.sharing_link], sep=args.separator)
> >   File "/home/wangyuxi/miniconda3/envs/lama/lib/python3.6/site-packages/wldhx/yadisk_direct/main.py", line 23, in <listcomp>
> >     print(*[get_real_direct_link(x) for x in args.sharing_link], sep=args.separator)
> >   File "/home/wangyuxi/miniconda3/envs/lama/lib/python3.6/site-packages/wldhx/yadisk_direct/main.py", line 12, in get_real_direct_link
> >     return pk_request.json()['href']
> > KeyError: 'href'
> > curl: no URL specified!
> > curl: try 'curl --help' or 'curl --manual' for more information
> > ```
> 
> Whether you have solved？
Not yet : /

**Comment by maazullah96** [comment]
Link for the pretrained model i find it from this repository https://github.com/geekyutao/inpaint-anything
you can try downloading the model from  this link the results are not quite good as i need .I think this link would be useful for you to run the code 
https://drive.google.com/drive/folders/1wpY-upCo4GIW4wVPnlMh_ym779lLIG2A

**Comment by imbinwang** [comment]
> Link for the pretrained model i find it from this repository https://github.com/geekyutao/inpaint-anything you can try downloading the model from this link the results are not quite good as i need .I think this link would be useful for you to run the code https://drive.google.com/drive/folders/1wpY-upCo4GIW4wVPnlMh_ym779lLIG2A

Works for me. Thanks!

**Comment by Nineves** [comment]
> Link for the pretrained model i find it from this repository https://github.com/geekyutao/inpaint-anything you can try downloading the model from this link the results are not quite good as i need .I think this link would be useful for you to run the code https://drive.google.com/drive/folders/1wpY-upCo4GIW4wVPnlMh_ym779lLIG2A

Thank you!

**Comment by linghuyuhangyuan** [comment]
> Link for the pretrained model i find it from this repository https://github.com/geekyutao/inpaint-anything you can try downloading the model from this link the results are not quite good as i need .I think this link would be useful for you to run the code https://drive.google.com/drive/folders/1wpY-upCo4GIW4wVPnlMh_ym779lLIG2A

Do you find pretrained model for CelebaHQ Dataset ?
