### ISSUE TITLE
Cant download the model weight. 

### ISSUE THREAD

**Issue by RupertLuo** [advimman/lama#273]
Hi, this is a great job, but the download link of the model is invalid. Is there a new link, or can someone send me a copy of the weights? My email is 1225457706@qq.com.

**Comment by 20km-shimakaze** [comment]
> Hi, this is a great job, but the download link of the model is invalid. Is there a new link, or can someone send me a copy of the weights? My email is [1225457706@qq.com](mailto:1225457706@qq.com).嗨，这是一项很棒的工作，但是模型的下载链接无效。是否有新链接，或者有人可以向我发送砝码的副本吗？我的电子邮件已 1225457706@qq.com。

download on Huggingface, just search 'big-lama', you will find the model

**Comment by senya-ashukha** [comment]
Sorry for inconvenience ---- try that https://drive.google.com/drive/folders/1B2x7eQDgecTL0oh3LSIBDGj0fTxs6Ips?usp=drive_link ! 
and we will fix the repo! TY!
