### ISSUE TITLE
Could not initialize NNPACK! Reason: Unsupported hardware.

### ISSUE THREAD

**Issue by DNucX** [advimman/lama#277]
Hello,

First all I want to say thank you for such a great project! :)

When the process is done, I get the follow warning/error:

`[W NNPACK.cpp:80] Could not initialize NNPACK! Reason: Unsupported hardware.`

Everything works fine though, which I am glad about. I am able to remove an object from an image with no issues. However, the only thing is upon completion, the above warning/error is mentioned. Is this something that needs correcting/fixing? If so, how? Or is this a warning/error that's okay to ignore?

Thank you in advance!

**Comment by senya-ashukha** [comment]
Hey that is probably OK https://discuss.pytorch.org/t/bug-w-nnpack-cpp-80-could-not-initialize-nnpack-reason-unsupported-hardware/107518
