### ISSUE TITLE
pretrained model weight download link invalid

### ISSUE THREAD

**Issue by TimChou-ntu** [advimman/lama#290]
Hi, thanks for your awesome work.
I found that the download link (https://disk.yandex.ru/d/EgqaSnLohjuzAg) for the pre-trained model weight is not working. Is there any possible way that I can get the big-lama model weight?

![image](https://github.com/advimman/lama/assets/67358795/373cfd6e-bafb-461a-87f6-c81ce6e53167)

Looking forward to your reply.
Thanks.

**Comment by TimChou-ntu** [comment]
Oh I found the other link that works. Thanks XD

**Comment by anandbhattad** [comment]
what is the other link? Thanks!

**Comment by huyidu** [comment]
what is the other link?
