### ISSUE TITLE
Can I fine-tune the model? 

### ISSUE THREAD

**Issue by Abbsalehi** [advimman/lama#299]
Dear Authors, 

Thanks for your good work. I am wondering if is it possible to fine-tune the model. If so, could you please let me know where can I call the trained checkpoint? thanks

**Comment by phourior** [comment]
I am also trying to finetune the pretrained model, could you please tell me how to do that?

**Comment by qwexacc** [comment]
> I am also trying to finetune the pretrained model, could you please tell me how to do that?

Hello, I am trying to run this model, have any questions can you communicate? My contact information QQ1011578192
