### ISSUE TITLE
about running predict.py

### ISSUE THREAD

**Issue by yyyyojiro** [advimman/lama#58]
Thanks for your brilliant work, and when I run predict.py, the errors occured.

Detectron v2 is not installed
mismatched input '(' expecting <EOF>
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
how could I solve it, thanks!

**Comment by windj007** [comment]
Hi! I'm not sure that I understand your problem and question. Could you please post the command you run and stack trace?

**Comment by SaiNikhileshReddy** [comment]
```shell
** Initial Lines from shell
Detectron v2 is not installed
[2021-12-13 01:26:17,758][saicinpainting.utils][WARNING] - Setting signal 10 handler <function print_traceback_handler at 0x7fee50be7040>
[2021-12-13 01:26:17,780][root][INFO] - Make training model default
[2021-12-13 01:26:17,780][saicinpainting.training.trainers.base][INFO] - BaseInpaintingTrainingModule init called
[2021-12-13 01:26:17,781][root][INFO] - Make generator ffc_resnet
[2021-12-13 01:26:18,175][saicinpainting.training.trainers.base][INFO] - Generator
FFCResNetGenerator(
  (model): Sequential(
    (0): ReflectionPad2d((3, 3, 3, 3))
    (1): FFC_BN_ACT(
      (ffc): FFC(
        (convl2l): Conv2d(4, 64, kernel_size=(7, 7), stride=(1, 1), bias=False, padding_mode=reflect)
        (convl2g): Identity()
        (convg2l): Identity()
        (convg2g): Identity()
        (gate): Identity()
      )
      
*** last few lines
    (33): ReflectionPad2d((3, 3, 3, 3))
    (34): Conv2d(64, 3, kernel_size=(7, 7), stride=(1, 1))
    (35): Sigmoid()
  )
)
[2021-12-13 01:26:18,175][saicinpainting.training.trainers.base][INFO] - BaseInpaintingTrainingModule init done
[2021-12-13 01:26:18,830][saicinpainting.training.data.datasets][INFO] - Make val dataloader default from /home/nikhilesh/Documents/AIE/5_semester/projects/MagicEraser/lama_model/input/

```

**Comment by SaiNikhileshReddy** [comment]
@yyyyojiro I have installed Detectron 2 as it was asking. Still, isn't working.
```shell
python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
```

**Comment by yyyyojiro** [comment]
> Hi! I'm not sure that I understand your problem and question. Could you please post the command you run and the stack trace?

thanks for your brilliant work and reply. I find that when I don't use gpu for predicting, it works. @SaiNikhileshReddy

**Comment by windj007** [comment]
Sorry for the late reply again))

> Detectron v2 is not installed

This is just a warning - it should not break training/prediction

> mismatched input '(' expecting 

This means that there is an error in any of the YAML files. Did you change any of the configs?

**Comment by ImmortalSdm** [comment]
> Thanks for your brilliant work, and when I run predict.py, the errors occured.
> 
> Detectron v2 is not installed mismatched input '(' expecting See https://hydra.cc/docs/next/advanced/override_grammar/basic for details
> 
> Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace. how could I solve it, thanks!

I'm facing the similar error:
`Detectron v2 is not installed

Bad key "text.kerning_factor" on line 4 in
/home/dmsheng/anaconda3/envs/lama/lib/python3.6/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution
Traceback (most recent call last):
  File "/home/dmsheng/anaconda3/envs/lama/lib/python3.6/site-packages/hydra/core/utils.py", line 77, in _save_config
    file.write(OmegaConf.to_yaml(cfg))
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.`

@windj007 any idea to solve the problem?

**Comment by windj007** [comment]
Hi!

That's strange... The lines about detectron and matplotlib are just warnings, they should not break anything.

Did you check the versions of the libraries installed and that they do not conflict with those set in requirements.txt?
 It seems that you have a different version of Hydra and/or OmegaConf, which we did not test our pipeline with.
 
Could you please run it as `HYDRA_FULL_ERROR=1 ./bin/predict.py ....` ?

**Comment by callanrocks** [comment]
I had the same error as the OP on Windows, fixed it by enter the arguments into configs/prediction/default.yaml and commenting out line 41 of predict.py

**Comment by ImmortalSdm** [comment]
> Hi!
> 
> That's strange... The lines about detectron and matplotlib are just warnings, they should not break anything.
> 
> Did you check the versions of the libraries installed and that they do not conflict with those set in requirements.txt? It seems that you have a different version of Hydra and/or OmegaConf, which we did not test our pipeline with.
> 
> Could you please run it as `HYDRA_FULL_ERROR=1 ./bin/predict.py ....` ?

I simply solve the problem by downgrade pyyaml to version 5.4. Thanks for your reply.

**Comment by windj007** [comment]
Hi! iIs the problem resolved currently? If yes, please let me know so I can close the issue

**Comment by Junital** [comment]
Hi, I got some problems. @windj007 

Detectron v2 is not installed
[2022-07-24 12:33:59,096][saicinpainting.utils][WARNING] - Setting signal 1 handler <function print_traceback_handler at 0x000002D268183DC0>
[2022-07-24 12:33:59,105][__main__][CRITICAL] - Prediction failed due to invalid signal value:
Traceback (most recent call last):
  File "bin/predict.py", line 41, in main
    register_debug_signal_handlers()  # kill -10 <pid> will result in traceback dumped into log
  File "D:\D\github\lama\saicinpainting\utils.py", line 109, in register_debug_signal_handlers
    signal.signal(sig, handler)
  File "D:\D\Anaconda\envs\lama\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: invalid signal value

Can you help me fixing this problem, please?

**Comment by abdullah-rashid62** [comment]
Command:` python bin/predict.py model.path=$(pwd)/big-lama indir=$(pwd)/LaMa_test_images outdir=$(pwd)/output`
Detectron v2 is not installed
mismatched input '(' expecting <EOF>
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
Still getting this error.

**Comment by abdullah-rashid62** [comment]
> I had the same error as the OP on Windows, fixed it by enter the arguments into configs/prediction/default.yaml and commenting out line 41 of predict.py

Can you please tell us the changes you make in  `configs/prediction/default.yaml` in detail?

**Comment by yumengWang112** [comment]
I have the same error,did someone solved it?

**Comment by LeoAKALiu** [comment]
> @windj007 I'm having a similar issue while I run the model on the local machine. Let me know what I should do about it.
> 
> ```shell
> ** Initial Lines from shell
> Detectron v2 is not installed
> [2021-12-13 01:26:17,758][saicinpainting.utils][WARNING] - Setting signal 10 handler <function print_traceback_handler at 0x7fee50be7040>
> [2021-12-13 01:26:17,780][root][INFO] - Make training model default
> [2021-12-13 01:26:17,780][saicinpainting.training.trainers.base][INFO] - BaseInpaintingTrainingModule init called
> [2021-12-13 01:26:17,781][root][INFO] - Make generator ffc_resnet
> [2021-12-13 01:26:18,175][saicinpainting.training.trainers.base][INFO] - Generator
> FFCResNetGenerator(
>   (model): Sequential(
>     (0): ReflectionPad2d((3, 3, 3, 3))
>     (1): FFC_BN_ACT(
>       (ffc): FFC(
>         (convl2l): Conv2d(4, 64, kernel_size=(7, 7), stride=(1, 1), bias=False, padding_mode=reflect)
>         (convl2g): Identity()
>         (convg2l): Identity()
>         (convg2g): Identity()
>         (gate): Identity()
>       )
> *****
> Lines of model architecture
> *****   
> ** last few lines
>     (33): ReflectionPad2d((3, 3, 3, 3))
>     (34): Conv2d(64, 3, kernel_size=(7, 7), stride=(1, 1))
>     (35): Sigmoid()
>   )
> )
> [2021-12-13 01:26:18,175][saicinpainting.training.trainers.base][INFO] - BaseInpaintingTrainingModule init done
> [2021-12-13 01:26:18,830][saicinpainting.training.data.datasets][INFO] - Make val dataloader default from /path/to/lama_model/input/
> ```

It's completely not the similar issue, man

**Comment by LeoAKALiu** [comment]
> @abdullah-rashid62 I just changed the indir/outdir/path lines from **no** to the paths I wanted to use instead of inputting them through CLI.

Put all configs into configs/prediction/defaults.yaml instead of CLI could solve the issue

**Comment by arnavmehta7** [comment]
Anyone found solution for windows?

**Comment by arnavmehta7** [comment]
> > @abdullah-rashid62 I just changed the indir/outdir/path lines from **no** to the paths I wanted to use instead of inputting them through CLI.
> 
> Put all configs into configs/prediction/defaults.yaml instead of CLI could solve the issue

Not working :(

**Comment by moniltusharshah** [comment]
To solve this issue you need to use this two steps,

Step-1: As @callanrocks mentioned, comment out line 41 of `predict.py`. 

Step-2: Issue on windows OS is, it requires full path instead of relative path. So in `predict.py`, go to line 45 where `train_config_path` is being set and add a line below it as `train_config_path = os.path.join('<your_full_path_to_lama_base_directory>', train_config_path)` and then go to line 54 where `checkpoint_path` is being set and add a line below it as, `checkpoint_path = os.path.join('<your_full_path_to_lama_base_directory>', checkpoint_path)`. This will allow the program to use full path instead of relative path. 

Doing so shall solve the issue.

**Comment by czh886** [comment]
> > 在本地计算机上运行模型时，我遇到了类似的问题。让我知道我应该怎么做。
> > ```shell
> > ** Initial Lines from shell
> > Detectron v2 is not installed
> > [2021-12-13 01:26:17,758][saicinpainting.utils][WARNING] - Setting signal 10 handler <function print_traceback_handler at 0x7fee50be7040>
> > [2021-12-13 01:26:17,780][root][INFO] - Make training model default
> > [2021-12-13 01:26:17,780][saicinpainting.training.trainers.base][INFO] - BaseInpaintingTrainingModule init called
> > [2021-12-13 01:26:17,781][root][INFO] - Make generator ffc_resnet
> > [2021-12-13 01:26:18,175][saicinpainting.training.trainers.base][INFO] - Generator
> > FFCResNetGenerator(
> >   (model): Sequential(
> >     (0): ReflectionPad2d((3, 3, 3, 3))
> >     (1): FFC_BN_ACT(
> >       (ffc): FFC(
> >         (convl2l): Conv2d(4, 64, kernel_size=(7, 7), stride=(1, 1), bias=False, padding_mode=reflect)
> >         (convl2g): Identity()
> >         (convg2l): Identity()
> >         (convg2g): Identity()
> >         (gate): Identity()
> >       )
> > *****
> > Lines of model architecture
> > *****   
> > ** last few lines
> >     (33): ReflectionPad2d((3, 3, 3, 3))
> >     (34): Conv2d(64, 3, kernel_size=(7, 7), stride=(1, 1))
> >     (35): Sigmoid()
> >   )
> > )
> > [2021-12-13 01:26:18,175][saicinpainting.training.trainers.base][INFO] - BaseInpaintingTrainingModule init done
> > [2021-12-13 01:26:18,830][saicinpainting.training.data.datasets][INFO] - Make val dataloader default from /path/to/lama_model/input/
> > ```
> 
> 这完全不是类似的问题，伙计

detectron2
I am also experiencing such a problem

**Comment by senya-ashukha** [comment]
TY @moniltusharshah !

**Comment by sssjjjmmm** [comment]
I solved it this way by creating a new sub folder named 'label' in the data folder, and then putting the mask into this sub folder.
