### ISSUE TITLE
[Proposal] Proposal for a better code hygiene

### ISSUE THREAD

**Issue by ternaus** [advimman/lama#72]
Hi, I love the project, and the code quality is relatively high. 

But there could be a few more minor steps to make it even more readable.

Could you please consider adding 
* formatters: [black](https://github.com/psf/black), [isort](https://github.com/PyCQA/isort)
* linters: [flake8](https://flake8.pycqa.org/en/latest/), [pylint](https://pylint.org/), [mypy](https://github.com/python/mypy)

to the project?

+ [pre-commit hook](https://pre-commit.com/)
+ GitHub actions to check for it on every PR?

It should be relatively straightforward and will not change any code logic but benefit maintainers and other users.

At some point, I wrote a blog post on the topic with examples of all the steps: [I trained a model. What is next?](https://medium.com/kaggle-blog/i-trained-a-model-what-is-next-d1ba1c560e26)

Or you can see how we do it in Albumentations: [https://github.com/albumentations-team/albumentations](https://github.com/albumentations-team/albumentations)

The repository will also become a role model for all other Research Projects at GitHub :)

P.S. If you consider doing this and encounter problems, I will be happy to answer any questions.

**Comment by windj007** [comment]
Hi! Sorry for the late reply and thank you for the ideas - they are perfectly reasonable and worth doing! We'll try to find time to implement that
