### ISSUE TITLE
Streamlit implementation

### ISSUE THREAD

**Issue by petergro-hub** [advimman/lama#94]
Hey there, thanks for making the code & model public.
I've made a small streamlit tool out of it, together with seam-carving for image retargeting.
It's currently quite rudimentary but I'll add new features soon.

https://github.com/petergro-hub/ComicInpainting

**Comment by windj007** [comment]
Hi! Thank you very much for sharing your repo! Could you please illustrate, what you app does? Maybe add a couple of screenshots to readme?

After that, I'll be happy to add your repo to our README as well!

**Comment by petergro-hub** [comment]
Hi I will still update the GUI, once that's finalized I'll add more documentation and ping this issue again, thanks

**Comment by 2blackbar** [comment]
It wont setup env
Solving environment: failed

ResolvePackageNotFound:

**Comment by windj007** [comment]
@2blackbar it might be more reasonable to file an issue in @petergro-hub repo
